# This file was generated by GoReleaser. DO NOT EDIT.
class EksctlPrivate < Formula
  desc "The official CLI for Amazon EKS"
  homepage "https://eksctl.io/"
  version "0.19.0"

  if OS.mac?
    url "https://github.com/weaveworks/eksctl-private/releases/download/0.19.0/eksctl_Darwin_amd64.tar.gz"
    sha256 "94eddd61cc63043295bfdbd68c3c2d7d130dd52cbbbd921217fb403fa62f3b04"
  elsif OS.linux?
    url "https://github.com/weaveworks/eksctl-private/releases/download/0.19.0/eksctl_Linux_amd64.tar.gz"
    sha256 "1404a81a057cd145308c188d76c647d834f747cdea6434bb1865375c97a31594"
  end
  
  head "https://github.com/weaveworks/eksctl-private/releases/download/latest_release/eksctl_Darwin_amd64.tar.gz"
  
  depends_on "kubernetes-cli"
  depends_on "aws-iam-authenticator"

  def install
    bin.install "eksctl"
  end
end
