# This file was generated by GoReleaser. DO NOT EDIT.
class Eksctl < Formula
  desc "The official CLI for Amazon EKS"
  homepage "https://eksctl.io/"
  version "0.36.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/weaveworks/eksctl/releases/download/0.36.0/eksctl_Darwin_amd64.tar.gz"
    sha256 "cb5359d35271296ba547ee98d521d8726ac10bd84ba40c3e2a0f8601e4ffcc6c"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/weaveworks/eksctl/releases/download/0.36.0/eksctl_Linux_amd64.tar.gz"
    sha256 "8bc1618ca343c92d65e879c0f824fe67bcb0c388515678e0068a206626a620b3"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/weaveworks/eksctl/releases/download/0.36.0/eksctl_Linux_armv6.tar.gz"
    sha256 "6c0d876afe97bd16c38ed97b063408cc83286c0c470cf1077a6473891b63e5de"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/weaveworks/eksctl/releases/download/0.36.0/eksctl_Linux_arm64.tar.gz"
    sha256 "19c8ebd8bc724bd1cdc6d19bc11ea3f37db103964aa6f7f3fd1b65e8a0bb5b03"
  end

  head "https://github.com/weaveworks/eksctl/releases/download/latest_release/eksctl_Darwin_amd64.tar.gz"

  depends_on "kubernetes-cli"
  depends_on "aws-iam-authenticator"

  def install
    bin.install "eksctl"

    # Install bash completion
    output = Utils.popen_read("#{bin}/eksctl completion bash")
    (bash_completion/"eksctl").write output

    # Install zsh completion
    output = Utils.popen_read("#{bin}/eksctl completion zsh")
    (zsh_completion/"_eksctl").write output
  end
end
