# This file was generated by GoReleaser. DO NOT EDIT.
class EksctlPrivate < Formula
  desc "The official CLI for Amazon EKS"
  homepage "https://eksctl.io/"
  version "latest_release"

  if OS.mac?
    url "https://github.com/weaveworks/eksctl-private/releases/download/latest_release/eksctl_Darwin_amd64.tar.gz"
    sha256 "170f33bf54a5ee6144a78f79f946d67a309037b09d0f8e906ff660e15c3df9c0"
  elsif OS.linux?
    url "https://github.com/weaveworks/eksctl-private/releases/download/latest_release/eksctl_Linux_amd64.tar.gz"
    sha256 "9addbef0b9aa099939178119b6cab12b2a909402289e23d92fcb15c0b4e28ab6"
  end
  
  head https://github.com/weaveworks/eksctl/releases/download/latest_release/eksctl_Darwin_amd64.tar.gz
  
  depends_on "kubernetes-cli"
  depends_on "aws-iam-authenticator"

  def install
    bin.install "eksctl"
  end
end
