# This file was generated by GoReleaser. DO NOT EDIT.
class Footloose < Formula
  desc "Containers that look like Virtual Machines"
  homepage "https://github.com/weaveworks/footloose"
  url "https://github.com/weaveworks/footloose/releases/download/0.5.0/footloose-0.5.0-darwin-x86_64.tar.gz"
  version "0.5.0"
  sha256 "0b989621b8141dd31eb90fe0bb3aa5a12147a807dd86e7d33c990ec69e380550"

  def install
    bin.install "footloose"
  end
end
