# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitops < Formula
  desc "GitOps support for Kubernetes"
  homepage "https://docs.gitops.weave.works/docs/getting-started"
  version "0.31.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/weaveworks/weave-gitops/releases/download/v0.31.1/gitops-Darwin-x86_64.tar.gz"
      sha256 "807a15cd30b6d37f907172133c8caff05150382e25f989fca770c1eae22c3bc6"

      def install
        bin.install "gitops"
        # Install bash completion
        output = Utils.safe_popen_read({ "SHELL" => "bash" }, "#{bin}/gitops completion bash --no-analytics", { :err => :err })
        (bash_completion/"gitops").write output

        # Install zsh completion
        output = Utils.safe_popen_read({ "SHELL" => "zsh" }, "#{bin}/gitops completion zsh --no-analytics", { :err => :err })
        (zsh_completion/"_gitops").write output
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/weaveworks/weave-gitops/releases/download/v0.31.1/gitops-Darwin-arm64.tar.gz"
      sha256 "932c3399c987d99c5808710168b7e167a0baa1a8dd149ede7a183d5168c40127"

      def install
        bin.install "gitops"
        # Install bash completion
        output = Utils.safe_popen_read({ "SHELL" => "bash" }, "#{bin}/gitops completion bash --no-analytics", { :err => :err })
        (bash_completion/"gitops").write output

        # Install zsh completion
        output = Utils.safe_popen_read({ "SHELL" => "zsh" }, "#{bin}/gitops completion zsh --no-analytics", { :err => :err })
        (zsh_completion/"_gitops").write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/weaveworks/weave-gitops/releases/download/v0.31.1/gitops-Linux-arm64.tar.gz"
      sha256 "a8183d99bd97d485a528572c540086334a6d2e8667b6589c7388e78c662fe4d9"

      def install
        bin.install "gitops"
        # Install bash completion
        output = Utils.safe_popen_read({ "SHELL" => "bash" }, "#{bin}/gitops completion bash --no-analytics", { :err => :err })
        (bash_completion/"gitops").write output

        # Install zsh completion
        output = Utils.safe_popen_read({ "SHELL" => "zsh" }, "#{bin}/gitops completion zsh --no-analytics", { :err => :err })
        (zsh_completion/"_gitops").write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/weaveworks/weave-gitops/releases/download/v0.31.1/gitops-Linux-x86_64.tar.gz"
      sha256 "dfb00e8200f9fdb9b2bf5fdf252e8ca49f5898dc542116051dc2e58b0dc3be12"

      def install
        bin.install "gitops"
        # Install bash completion
        output = Utils.safe_popen_read({ "SHELL" => "bash" }, "#{bin}/gitops completion bash --no-analytics", { :err => :err })
        (bash_completion/"gitops").write output

        # Install zsh completion
        output = Utils.safe_popen_read({ "SHELL" => "zsh" }, "#{bin}/gitops completion zsh --no-analytics", { :err => :err })
        (zsh_completion/"_gitops").write output
      end
    end
  end
end
