# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitops < Formula
  desc "GitOps support for Kubernetes"
  homepage "https://docs.gitops.weave.works/docs/getting-started"
  version "0.16.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/weaveworks/weave-gitops/releases/download/v0.16.0/gitops-darwin-x86_64.tar.gz"
      sha256 "6320fd45be81b7880f496964a1f57d1d4f7ea7e20b804e812affd67fde402021"

      def install
        bin.install "gitops"
        # Install bash completion
        output = Utils.safe_popen_read({ "SHELL" => "bash" }, "#{bin}/gitops completion bash --no-analytics", { :err => :err })
        (bash_completion/"gitops").write output

        # Install zsh completion
        output = Utils.safe_popen_read({ "SHELL" => "zsh" }, "#{bin}/gitops completion zsh --no-analytics", { :err => :err })
        (zsh_completion/"_gitops").write output
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/weaveworks/weave-gitops/releases/download/v0.16.0/gitops-darwin-arm64.tar.gz"
      sha256 "834558f1e319df5a3a1f28328bdc9345f7119f0a892bef1ad0bbc28e60294cbf"

      def install
        bin.install "gitops"
        # Install bash completion
        output = Utils.safe_popen_read({ "SHELL" => "bash" }, "#{bin}/gitops completion bash --no-analytics", { :err => :err })
        (bash_completion/"gitops").write output

        # Install zsh completion
        output = Utils.safe_popen_read({ "SHELL" => "zsh" }, "#{bin}/gitops completion zsh --no-analytics", { :err => :err })
        (zsh_completion/"_gitops").write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/weaveworks/weave-gitops/releases/download/v0.16.0/gitops-linux-arm64.tar.gz"
      sha256 "dd48248956669ec1700666b8725d69fdc5bf2f9cd4eb9fae637711a0a8821d14"

      def install
        bin.install "gitops"
        # Install bash completion
        output = Utils.safe_popen_read({ "SHELL" => "bash" }, "#{bin}/gitops completion bash --no-analytics", { :err => :err })
        (bash_completion/"gitops").write output

        # Install zsh completion
        output = Utils.safe_popen_read({ "SHELL" => "zsh" }, "#{bin}/gitops completion zsh --no-analytics", { :err => :err })
        (zsh_completion/"_gitops").write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/weaveworks/weave-gitops/releases/download/v0.16.0/gitops-linux-x86_64.tar.gz"
      sha256 "9ba75be4f42e51124479cfc66a22becb8f63fe47a3eb7a01e58701e8f8d22e6d"

      def install
        bin.install "gitops"
        # Install bash completion
        output = Utils.safe_popen_read({ "SHELL" => "bash" }, "#{bin}/gitops completion bash --no-analytics", { :err => :err })
        (bash_completion/"gitops").write output

        # Install zsh completion
        output = Utils.safe_popen_read({ "SHELL" => "zsh" }, "#{bin}/gitops completion zsh --no-analytics", { :err => :err })
        (zsh_completion/"_gitops").write output
      end
    end
  end
end
