# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitops < Formula
  desc "GitOps support for Kubernetes"
  homepage "https://docs.gitops.weave.works/docs/getting-started"
  version "0.26.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/weaveworks/weave-gitops/releases/download/v0.26.0/gitops-darwin-x86_64.tar.gz"
      sha256 "eba8f58ac0a1af7f186c22163fdbf61251c340055683eecd91dd877fa7ba81f4"

      def install
        bin.install "gitops"
        # Install bash completion
        output = Utils.safe_popen_read({ "SHELL" => "bash" }, "#{bin}/gitops completion bash --no-analytics", { :err => :err })
        (bash_completion/"gitops").write output

        # Install zsh completion
        output = Utils.safe_popen_read({ "SHELL" => "zsh" }, "#{bin}/gitops completion zsh --no-analytics", { :err => :err })
        (zsh_completion/"_gitops").write output
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/weaveworks/weave-gitops/releases/download/v0.26.0/gitops-darwin-arm64.tar.gz"
      sha256 "976ee36da9b7a95ada46d55686e2164b3fb962fde42e17a46bb2b2f1cdc14d71"

      def install
        bin.install "gitops"
        # Install bash completion
        output = Utils.safe_popen_read({ "SHELL" => "bash" }, "#{bin}/gitops completion bash --no-analytics", { :err => :err })
        (bash_completion/"gitops").write output

        # Install zsh completion
        output = Utils.safe_popen_read({ "SHELL" => "zsh" }, "#{bin}/gitops completion zsh --no-analytics", { :err => :err })
        (zsh_completion/"_gitops").write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/weaveworks/weave-gitops/releases/download/v0.26.0/gitops-linux-arm64.tar.gz"
      sha256 "0c689c48d797e9fbf7609dc1b2df155d14655ab54bc9dcad66e84b4c536d3956"

      def install
        bin.install "gitops"
        # Install bash completion
        output = Utils.safe_popen_read({ "SHELL" => "bash" }, "#{bin}/gitops completion bash --no-analytics", { :err => :err })
        (bash_completion/"gitops").write output

        # Install zsh completion
        output = Utils.safe_popen_read({ "SHELL" => "zsh" }, "#{bin}/gitops completion zsh --no-analytics", { :err => :err })
        (zsh_completion/"_gitops").write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/weaveworks/weave-gitops/releases/download/v0.26.0/gitops-linux-x86_64.tar.gz"
      sha256 "33cade51f019e652b1cc412f98c3972882b2e0a8a05a6bc335e8d86277ee6fd0"

      def install
        bin.install "gitops"
        # Install bash completion
        output = Utils.safe_popen_read({ "SHELL" => "bash" }, "#{bin}/gitops completion bash --no-analytics", { :err => :err })
        (bash_completion/"gitops").write output

        # Install zsh completion
        output = Utils.safe_popen_read({ "SHELL" => "zsh" }, "#{bin}/gitops completion zsh --no-analytics", { :err => :err })
        (zsh_completion/"_gitops").write output
      end
    end
  end
end
