# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfctl < Formula
  desc ""
  homepage "https://weaveworks.github.io/tf-controller"
  version "0.11.0-rc.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/weaveworks/tf-controller/releases/download/v0.11.0-rc.2/tfctl_Darwin_arm64.tar.gz"
      sha256 "1f32b51b39d57862188580044c7378eb4a9c9dd77ec78aaaf7e0abc475f337d7"

      def install
        bin.install "tfctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/weaveworks/tf-controller/releases/download/v0.11.0-rc.2/tfctl_Darwin_amd64.tar.gz"
      sha256 "5ca82ff6cbc4d9956c51181adb27f04312330fbaf1baf62f418341004be89e0a"

      def install
        bin.install "tfctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/weaveworks/tf-controller/releases/download/v0.11.0-rc.2/tfctl_Linux_arm64.tar.gz"
      sha256 "322726cb561b41fc63f4085836f132fefbeb50fcde9d4fcf7c5d07ef9d85f999"

      def install
        bin.install "tfctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/weaveworks/tf-controller/releases/download/v0.11.0-rc.2/tfctl_Linux_amd64.tar.gz"
      sha256 "f56930c006a9d7bb14aa9d992cb1e016eae8cb9841d4cfef20de639898722f4a"

      def install
        bin.install "tfctl"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/weaveworks/tf-controller/releases/download/v0.11.0-rc.2/tfctl_Linux_armv6.tar.gz"
      sha256 "b289e0560fb916bd5723ad47ebde85fe736d5393d8011ceb77146b2908fa8eff"

      def install
        bin.install "tfctl"
      end
    end
  end
end
