# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfctl < Formula
  desc ""
  homepage "https://weaveworks.github.io/tf-controller"
  version "0.11.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/weaveworks/tf-controller/releases/download/v0.11.0/tfctl_Darwin_amd64.tar.gz"
      sha256 "653fc909217c42919922ae1050df714257efe90f0b012938e3f84275ca12112e"

      def install
        bin.install "tfctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/weaveworks/tf-controller/releases/download/v0.11.0/tfctl_Darwin_arm64.tar.gz"
      sha256 "77794ba626a82933fae4e5872049042071d4d2d40be5320249b099694443bfed"

      def install
        bin.install "tfctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/weaveworks/tf-controller/releases/download/v0.11.0/tfctl_Linux_arm64.tar.gz"
      sha256 "499fb1579b0ad033babb392774d9febda704271567a25a1727e969f1deeb78d1"

      def install
        bin.install "tfctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/weaveworks/tf-controller/releases/download/v0.11.0/tfctl_Linux_amd64.tar.gz"
      sha256 "a05b4030de2f77adc98c6738fd18de9a1f9cdbc1130a72ad1cae523eae51f4bb"

      def install
        bin.install "tfctl"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/weaveworks/tf-controller/releases/download/v0.11.0/tfctl_Linux_armv6.tar.gz"
      sha256 "6da6f4081843cfc020d6f4884d9975630839e3d02d7731f3144ed001f31b66d5"

      def install
        bin.install "tfctl"
      end
    end
  end
end
