# This file was generated by GoReleaser. DO NOT EDIT.
class Wksctl < Formula
  desc "Open Source Weaveworks Kubernetes System"
  homepage "https://github.com/weaveworks/wksctl"
  url "https://github.com/weaveworks/wksctl/releases/download/0.8.1/wksctl-0.8.1-darwin-x86_64.tar.gz"
  version "0.8.1"
  sha256 "a3f413c25e5fb68cdc65cf51c3e5347bed1f4dc56c863d86f43b9e520a8ef4b0"

  def install
    bin.install "wksctl"
  end
end
